### ISSUE TITLE
#backbone

### ISSUE THREAD

**Issue by Yysheepsheep** [ennheng/UltraFastLaneDetectionv2_CBAM#1]
你好 我想问一下有尝试过把ufldv2的backbone换成其他的模型嘛

**Comment by ennheng** [comment]
可以替换的 resnet系列的可以直接替换 换其他的就得修改参数了

**Comment by ennheng** [comment]
去看这个仓库的原作者 那里有你想要的 我也是看那些issue鼓捣的

**Comment by Yysheepsheep** [comment]
好的 谢谢啦 我是在原作者下面看到你的评论追过来的

**Comment by Yysheepsheep** [comment]
我是想换除了resnet系列的别的网络 比如你在评论下面提到的moblienet

**Comment by ennheng** [comment]
这个我没换成功

**Comment by Yysheepsheep** [comment]
好的 谢谢啦 其他的轻量级网络有尝试嘛 我是比较菜的 不好意思了

**Comment by ennheng** [comment]
我试过换成其他的 但是f1下降了😹😹 最后就加了注意力机制 虽然也是下降了 但总算有了创新点。这个不大难 我没学过 最后都炼出来丹了😹😹

**Comment by ennheng** [comment]
换骨干网络得调整通道参数 让前后一样 这就得把代码看懂了

**Comment by Yysheepsheep** [comment]
对对对 主要就是创新点 真的是难为死 注意力是自己编的那种嘛还是现有的  好的好的 感谢 我还是想试一下moblienet 这个是不太行嘛

**Comment by ennheng** [comment]
我感觉比较重要的代码是model里model_culane那个 那里面有调整通道参数的

**Comment by Yysheepsheep** [comment]
我想用的数据集是tusimple

**Comment by ennheng** [comment]
注意力机制是可以直接插入的 我这里应该有代码 你可以看看 不过跑出来的相比原作者是更差了 不过你可以自己把基准 也就是对比的 降低点 这样你看着就像是有提升

**Comment by ennheng** [comment]
图森数据集还是比较简单的 数据量小 culane太大了 也复杂的多

**Comment by ennheng** [comment]
注意力机制是现成的 你只要把参数调好 就能跑出来东西了

**Comment by Yysheepsheep** [comment]
好的好的 我现在还停留在理论阶段 不太敢实践 动代码

**Comment by ennheng** [comment]
你加我微信吧 这里太麻烦了shutture

**Comment by Yysheepsheep** [comment]
好的好的

**Comment by cxuucx** [comment]
> 你加我微信吧 这里太麻烦了shutture

ennheng哥，可以加你一起学习进步吗

**Comment by ennheng** [comment]
我已经不搞这个了 毕业了

**Comment by cxuucx** [comment]
> 我已经不搞这个了 毕业了

好吧哥，能向您请教一下吗，小白实在好多东西不大懂

**Comment by cxuucx** [comment]
Yysheepsheep老哥你也是车道线检测这个方向吗，能一起交流学习下吗

**Comment by Yysheepsheep** [comment]
你好，还交流一下嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月20日(星期一) 晚上8:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [ennheng/UltraFastLaneDetectionv2_CBAM] #backbone (Issue #1)





 
Yysheepsheep老哥你也是车道线检测这个方向吗，能一起交流学习下吗

**Comment by cxuucx** [comment]
> 你好，还交流一下嘛
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年11月20日(星期一) 晚上8:12 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [ennheng/UltraFastLaneDetectionv2_CBAM] #backbone (Issue #1) Yysheepsheep老哥你也是车道线检测这个方向吗，能一起交流学习下吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

好的，你加我吧
cxuucx
